var BAAAHS = {
    Geometry: {
        PANEL_MAP: [
            ['20D', 'D', 'Tenderloin'],
            ['40D', 'D', 'Dock'],
            ['1D', 'D', 'Breast'],
            ['21D', 'D', 'Primary Mount'],
            ['41D', 'D', 'Hock'],
            ['2D', 'D', 'Breast'],
            ['22D', 'D', 'Flank'],
            ['42D', 'D', 'Hock'],
            ['F3D', 'D', 'Breast'],
            ['3D', 'D', 'Foreshank'],
            ['23D', 'D', 'Belly'],
            ['43D', 'D', 'Leg'],
            ['F4D', 'D', 'Breast'],
            ['4D', 'D', 'Shoulder'],
            ['24D', 'D', 'Loin'],
            ['F5D', 'D', 'Foreshank'],
            ['5D', 'D', 'Shoulder'],
            ['25D', 'D', 'Loin'],
            ['F6D', 'D', 'Foreshank'],
            ['6D', 'D', 'Shoulder'],
            ['26D', 'D', 'Loin'],
            ['F7D', 'D', 'Fore Hoof'],
            ['7D', 'D', 'Primary Mount'],
            ['27D', 'D', 'Ribs'],
            ['8D', 'D', 'Foreshank'],
            ['28D', 'D', 'Ribs'],
            ['9D', 'D', 'Foreshank'],
            ['29D', 'D', 'Ribs'],
            ['F10D', 'D', 'Neck'],
            ['10D', 'D', 'Fore Hoof'],
            ['30D', 'D', 'Flank'],
            ['F11', '', 'Brow'],
            ['11D', 'D', 'Shoulder'],
            ['31D', 'D', 'Flank'],
            ['F12D', 'D', 'Brow'],
            ['12D', 'D', 'Shoulder'],
            ['32D', 'D', 'Rump'],
            ['R1', '', 'Dock'],
            ['F13D', 'D', 'Cheek'],
            ['13D', 'D', 'Rack'],
            ['33D', 'D', 'Leg'],
            ['R2D', 'D', 'Dock'],
            ['F14D', 'D', 'Cheek'],
            ['14D', 'D', 'Belly'],
            ['34D', 'D', 'Leg'],
            ['R3D', 'D', 'Twist'],
            ['F15', '', 'Neck'],
            ['15D', 'D', 'Rack'],
            ['35D', 'D', 'Hock'],
            ['R4D', 'D', 'Twist'],
            ['F16D', 'D', 'Head'],
            ['16D', 'D', 'Rack'],
            ['36D', 'D', 'Leg'],
            ['R5D', 'D', 'Twist'],
            ['F17D', 'D', 'Head'],
            ['17D', 'D', 'Primary Mount'],
            ['37D', 'D', 'Leg'],
            ['R6D', 'D', 'Twist'],
            ['F18D', 'D', 'Head'],
            ['18D', 'D', 'Belly'],
            ['38D', 'D', 'Hind Hoof'],
            ['R7D', 'D', 'Hock'],
            ['F19D', 'D', 'Head'],
            ['19D', 'D', 'Back'],
            ['39D', 'D', 'Dock'],
            ['F20D', 'D', 'Head'],
            ['20P', 'P', 'Tenderloin'],
            ['40P', 'P', 'Dock'],
            ['1P', 'P', 'Breast'],
            ['21P', 'P', 'Primary Mount'],
            ['41P', 'P', 'Hock'],
            ['2P', 'P', 'Breast'],
            ['22P', 'P', 'Flank'],
            ['42P', 'P', 'Hock'],
            ['F3P', 'P', 'Breast'],
            ['3P', 'P', 'Breast'],
            ['23P', 'P', 'Belly'],
            ['43P', 'P', 'Leg'],
            ['F4P', 'P', 'Breast'],
            ['F1P', 'P', 'Breast'],
            ['F1D', 'D', 'Breast'],
            ['F2P', 'P', 'Breast'],
            ['F2D', 'D', 'Breast'],
            ['F5P', 'P', 'Breast'],
            ['F22P', 'P', 'Neck'],
            ['F22D', 'D', 'Neck'],
            ['F23P', 'P', 'Neck'],
            ['F23D', 'D', 'Neck'],
            ['F24P', 'P', 'Neck'],
            ['F24D', 'D', 'Neck'],
            ['F25', '', 'Neck'],
            ['4P', 'P', 'Shoulder'],
            ['24P', 'P', 'Loin'],
            ['5P', 'P', 'Shoulder'],
            ['19AP', 'P', 'Back'],
            ['6P', 'P', 'Shoulder'],
            ['26P', 'P', 'Loin'],
            ['19BP', 'P', 'Back'],
            ['7P', 'P', 'Primary Mount'],
            ['27P', 'P', 'Ribs'],
            ['25AP', 'P', 'Loin'],
            ['8P', 'P', 'Foreshank'],
            ['28P', 'P', 'Ribs'],
            ['25BP', 'P', 'Loin'],
            ['9P', 'P', 'Foreshank'],
            ['29P', 'P', 'Ribs'],
            ['F10P', 'P', 'Neck'],
            ['10P', 'P', 'Fore Hoof'],
            ['30P', 'P', 'Flank'],
            ['11P', 'P', 'Shoulder'],
            ['31P', 'P', 'Flank'],
            ['F12P', 'P', 'Brow'],
            ['12P', 'P', 'Shoulder'],
            ['32P', 'P', 'Rump'],
            ['F13P', 'P', 'Cheek'],
            ['13P', 'P', 'Rack'],
            ['33P', 'P', 'Leg'],
            ['R2P', 'P', 'Dock'],
            ['F14P', 'P', 'Cheek'],
            ['14P', 'P', 'Belly'],
            ['34P', 'P', 'Leg'],
            ['R3P', 'P', 'Twist'],
            ['15P', 'P', 'Rack'],
            ['35P', 'P', 'Hock'],
            ['R4P', 'P', 'Twist'],
            ['F16P', 'P', 'Head'],
            ['16P', 'P', 'Rack'],
            ['36P', 'P', 'Leg'],
            ['R5P', 'P', 'Twist'],
            ['F17P', 'P', 'Head'],
            ['17P', 'P', 'Primary Mount'],
            ['37P', 'P', 'Leg'],
            ['R6P', 'P', 'Twist'],
            ['F18P', 'P', 'Head'],
            ['18P', 'P', 'Belly'],
            ['38P', 'P', 'Hind Hoof'],
            ['R7P', 'P', 'Hock'],
            ['F19P', 'P', 'Head'],
            ['39P', 'P', 'Dock'],
            ['F20P', 'P', 'Head']
        ],
        SECTION_COLORS: {
            "Back": "#ffbb99",
            "Belly": "#ffaaff",
            "Breast": "#ffbb99",
            "Brow": "#aaaaff",
            "Cheek": "#aaffaa",
            "Dock": "#aaaaff",
            "Rump": "#aaffff",
            "Flank": "#aaaaff",
            "Fore Hoof": "#666666",
            "Foreshank": "#aaaaff",
            "Head": "#ffaaff",
            "Hind Hoof": "#666666",
            "Hock": "#aaffaa",
            "Leg": "#ffaaaa",
            "Loin": "#ffffaa",
            "Tenderloin": "#aaaaff",
            "Neck": "#ffffaa",
            "Primary Mount": "#aaaaaa",
            "Rack": "#ffffaa",
            "Ribs": "#aaffaa",
            "Shoulder": "#aaffaa",
            "Twist": "#ffaaff",

            "Face": "#666666"
        }
    }
};
